config/routes.rb
AuthlogicSample::Application.routes.draw do
  resources :entries

  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  resources :users
  resource :user, as: 'account'

  match 'signup' => 'users#new', as: :signup

  root to: 'entries#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :title
end

app/models/role.rb
class Role < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :login, :password, :password_confirmation
  acts_as_authentic do |c|
    c.login_field = 'email'
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
# coidng: utf-8

class ApplicationController < ActionController::Base
  include TheRole::Requires

  protect_from_forgery

  def access_denied
    render text: 'access_denied: requires an role' and return
  end

  helper_method :current_user_session, :current_user

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  # ログインが必要なページに対する処理
  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_url
      return false
    end
  end

  # ログアウトが必要なページに対する処理
  def require_no_user
    if current_user
      store_location
      flash[:notice] = "You must be logged out to access this page"
      return false
    end
  end

  # ログイン/ログアウトの処理の前にいたページの情報を保存
  def store_location
    session[:return_to] = request.fullpath
  end

  # 処理が終わった後に戻るページを返す
  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
  
  alias_method :login_required, :require_user
  alias_method :role_access_denied, :access_denied
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_filter :require_user
  before_filter :role_required

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_sessions_controller.rb
# coding: utf-8

class UserSessionsController < ApplicationController
  before_filter :require_user, only: :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default account_url(@current_user)
    else
      render action: :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = "Your account has been created."
      redirect_to signup_url
    else
      flash[:notice] = "There was a problem creating you."
      render action: :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render action: :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.title %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/_header.html.erb
<header id="page_header">
  <% if current_user.nil? %>
    <%= link_to 'Sign up', signup_path %> or <%= link_to 'log in', login_path %>
  <% else %>
    <strong><%= current_user.email %></strong>がログイン中です。
    <%= link_to 'log out', logout_path, method: :delete %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthlogicSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login or <%= link_to 'Sign up', signup_path %></h1>
<%= form_for @user_session, as: :user_session, url: { action: 'create' } do |f| %>
  <%= f.label :email %> <%= f.text_field :email %><br />
  <%= f.label :password %> <%= f.password_field :password %><br />
  <%= f.check_box :remember_me %> remember me<br />
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/error_messages", target: @user %>

<p>
  <%= form.label :name %> <%= form.text_field :name %>
</p>
<p>
  <%= form.label :email %> <%= form.text_field :email %>
</p>
<p>
  <%= form.label :login %> <%= form.text_field :login %>
</p>
<p>
<%= form.label :password, form.object.new_record? ? nil : "Change password" %> <%= form.password_field :password %>
</p>
<p>
  <%= form.label :password_confirmation %> <%= form.password_field :password_confirmation %>
</p>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f| %>
  <%= render partial: "form", object: f, locals: { user: @user } %>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<p>
  <b>Email:</b><%= @user.email %>
</p>
<p>
  <b>Login count:</b><%= @user.login_count %>
</p>
<p>
  <b>Last request at:</b><%= @user.last_request_at %>
</p>
<p>
  <b>Last login at:</b><%= @user.last_login_at %>
</p>
<p>
  <b>Current login at:</b><%= @user.current_login_at %>
</p>
<p>
  <b>Last login ip:</b><%= @user.last_login_ip %>
</p>
<p>
  <b>Current login ip:</b><%= @user.current_login_ip %>
</p>

<%= link_to 'Edit Account', edit_account_path %>